"""add metric source and user table

Revision ID: 309a1933df3f
Revises: dfa4a25f4e9e
Create Date: 2026-07-13 19:11:11.197548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '309a1933df3f'
down_revision: Union[str, Sequence[str], None] = 'dfa4a25f4e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('client_id', sa.BigInteger(), nullable=False))
    op.alter_column('campaigns', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'campaigns', 'clients', ['client_id'], ['id'])
    op.drop_column('campaigns', 'client')
    op.add_column('metrics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('metrics', sa.Column('source', sa.Enum('user', 'system', name='metricsource'), nullable=False))
    op.alter_column('metrics', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('metrics', 'campaign_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'campaign_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('metrics', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('metrics', 'source')
    op.drop_column('metrics', 'created_at')
    op.add_column('campaigns', sa.Column('client', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('campaigns', 'client_id')
    # ### end Alembic commands ###
