"""add metric source and user table

Revision ID: 309a1933df3f
Revises: dfa4a25f4e9e
Create Date: 2026-07-13 19:11:11.197548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '309a1933df3f'
down_revision: Union[str, Sequence[str], None] = 'dfa4a25f4e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(inspector, table_name):
    return {c["name"]: c for c in inspector.get_columns(table_name)}


def _foreign_keys(inspector, table_name):
    return {tuple(fk["constrained_columns"]) for fk in inspector.get_foreign_keys(table_name)}


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "clients" not in inspector.get_table_names():
        op.create_table('clients',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        )
        inspector = sa.inspect(bind)

    campaigns_columns = _columns(inspector, "campaigns")
    metrics_columns = _columns(inspector, "metrics")

    if "client_id" not in campaigns_columns:
        op.add_column('campaigns', sa.Column('client_id', sa.BigInteger(), nullable=False))
    if isinstance(campaigns_columns.get("id", {}).get("type"), sa.INTEGER):
        op.alter_column('campaigns', 'id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    if isinstance(campaigns_columns.get("created_at", {}).get("type"), postgresql.TIMESTAMP) and not campaigns_columns.get("created_at", {}).get("type").timezone:
        op.alter_column('campaigns', 'created_at',
                   existing_type=postgresql.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=False,
                   existing_server_default=sa.text('now()'))
    if ("client_id",) not in _foreign_keys(inspector, "campaigns"):
        op.create_foreign_key(None, 'campaigns', 'clients', ['client_id'], ['id'])
    if "client" in campaigns_columns:
        op.drop_column('campaigns', 'client')

    if "created_at" not in metrics_columns:
        op.add_column('metrics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    if "source" not in metrics_columns:
        metric_source_enum = postgresql.ENUM('user', 'system', name='metricsource')
        metric_source_enum.create(bind, checkfirst=True)
        op.add_column('metrics', sa.Column('source', metric_source_enum, nullable=False))
    if isinstance(metrics_columns.get("id", {}).get("type"), sa.INTEGER):
        op.alter_column('metrics', 'id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    if isinstance(metrics_columns.get("campaign_id", {}).get("type"), sa.INTEGER):
        op.alter_column('metrics', 'campaign_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    op.alter_column('metrics', 'campaign_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('metrics', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('metrics', 'source')
    op.drop_column('metrics', 'created_at')
    op.add_column('campaigns', sa.Column('client', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('campaigns', 'client_id')
    if "clients" in inspector.get_table_names():
        op.drop_table('clients')
    # ### end Alembic commands ###
