"""add period_start and period_end to metrics

Revision ID: dfa4a25f4e9e
Revises: 62cee4a6b7ed
Create Date: 2026-04-20 17:12:38.451251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa4a25f4e9e'
down_revision: Union[str, Sequence[str], None] = '62cee4a6b7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('metrics', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('metrics', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE metrics SET period_start = '1970-01-01T00:00:00+00:00', period_end = '1970-01-01T00:00:00+00:00' WHERE period_start IS NULL")
    op.alter_column('metrics', 'period_start', nullable=False)
    op.alter_column('metrics', 'period_end', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'period_end')
    op.drop_column('metrics', 'period_start')

    # ### end Alembic commands ###
