# Campaign
CAMPAIGN_NAME_MIN_LENGTH = 1
CAMPAIGN_NAME_MAX_LENGTH = 200
CAMPAIGN_CLIENT_MIN_LENGTH = 1
CAMPAIGN_CLIENT_MAX_LENGTH = 200

# Pagination
PAGE_LIMIT_MIN = 1
PAGE_LIMIT_MAX = 100
PAGE_LIMIT_DEFAULT = 10
